inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Metrics/BlockLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
  AllowedMethods:
  - describe
  - context
  - shared_examples
  - RSpec::Matchers.define

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y
    - cr
    - x1
    - y1
    - x2
    - y2
