version: '3.4'

services:
  morandirb:
    image: morandirb
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/app'
    stdin_open: true
    tty: true
    command: bundle exec guard
